### ISSUE TITLE
android app crashes when open

### ISSUE THREAD

**Issue by DamianchoE** [Mewnojs/PlantsVsZombies.NET#5]
It crashes in the loading screen.

**Comment by Mewnojs** [comment]
Can't replicate. Make sure that your assets have been put into the right place `Lawn_Android/Assets/Content`, as missing them may cause crash.

**Comment by DamianchoE** [comment]
> Can't replicate. Make sure that your assets have been put into the right place `Lawn_Android/Assets/Content`, as missing them may cause crash.

I have the assets in the content folder and the game boots up normally in the "Plants VS Zombies" screen and then it crashes.
